### ISSUE TITLE
SAK 08 to 88 ?

### ISSUE THREAD

**Issue by Foul** [equipter/ClassicConverter#1]
Hi !
When i convert my badge, SAK 08 become SAK 88
Any idea why ?

Badge scanned with Flipper : 
![NFC](https://user-images.githubusercontent.com/829842/185802917-b074d281-e608-478d-a5cc-4d5f2bf9b2cd.png)

File converted from a Mifare Tools Dump :
https://pastebin.com/z0DZcTNn

**Comment by equipter** [comment]
sorry for the late reply 
this is because your tag has an anti cloning technique where the sak burned into the chip and the SAK in the block 0 are different. 

its very common and easy to fix

**Comment by Foul** [comment]
Interested by the fix ;)

**Comment by equipter** [comment]
> Interested by the fix ;)

unfortunately, the only fix is to manually edit the .nfc before you put it on your flipper (or take it off your flipper, change it and put it back) its just the SAK field that needs changing 

unfortunately this isn't something i can fix with code because it is working as intended, it is collecting the correct SAK from block 0, its just in this situation, the correct SAK is not the *true* SAK 

:(
